version: "3.4"
services:
 minio-console:
  build:
   context: .
   dockerfile: Dockerfile.release
  image: minio-console:1.0
  environment:
   - CONSOLE_MINIO_SERVER=http://172.31.8.148:9000
  entrypoint: ["/console", "server", "--port", "9001"]
  ports:
   - "9001:9001"